Traceback (most recent call last):

  File "/app/ETL.py", line 20, in <module>

    'UID=' + sa + ';'

NameError: name 'sa' is not defined
